### PR TITLE
Update snakeyaml to 1.27, clj-yaml to 0.7.2, tk-jetty9 to 4.1.2, and tk-metrics to 1.4.0

### PR DESCRIPTION
**Pull request by austb**

### CODE REVIEW

**Comment by Magisus** [comment]
Can we add Jetty 4.1.2 to this?

**Comment by austb** [comment]
Oh yep, I forgot to add that

**Review by Magisus — APPROVED** [review]

**Comment by Magisus** [comment]
Passed puppetserver's tests.

**Review by mwaggett — APPROVED** [review]

**Review by steveax — APPROVED** [review]
👍 

Passes on orchestrator and pe-rbac-service (2019.8.x)

**Pull request merged**
