### PR TITLE
(maint) Update puppetlabs/jdbc-util to 0.6.0

### PR DESCRIPTION
**Pull request by aperiodic**

### CODE REVIEW

**Comment by camlow325** [comment]
@aperiodic I'm happy to merge this if you'd like.  I'm pretty ignorant about jdbc-util.  Is there anyone else who should make the call on this - @pcarlisle or @jonathannewman?

**Comment by camlow325** [comment]
Oh, also, should this go to the since-created 0.4.x branch (for Glisan-specific work) or is master okay?

**Comment by aperiodic** [comment]
@camlow325 The only changes over the old version are some new utilities for creating & dropping databases & users, so it should be completely backwards-compatible. To that end, I don't think it's worth putting into 0.4.x

**Comment by jonathannewman** [comment]
+1 @camlow325

**Pull request merged**
