### PR TITLE
(PE-33913) change codeowners to dumpling

### PR DESCRIPTION
**Pull request by steveax**
Please add all notable changes to the "Unreleased" section of the CHANGELOG.

### CODE REVIEW

**Comment by mwaggett** [comment]
This should target 4.x and then we can merge up to main.

**Comment by mwaggett** [comment]
oh, I see you made a separate PR

**Comment by mwaggett** [comment]
I still think we should do a mergeup rather than have this separate PR just to bump in main.

**Comment by steveax** [comment]
Given the desire to _not_ have us push directly I don't see any advantage to the git timeline from a mergeup, but if you prefer: https://github.com/puppetlabs/clj-parent/pull/344

**Comment by steveax** [comment]
Closed in favor of #344

**Comment by mwaggett** [comment]
I always open PRs for mergeups anyway ¯\_(ツ)_/¯

**Pull request closed without merging**
