### PR TITLE
(PE-33226) Update pgjdbc to fix bug when used with Bouncy Castle

### PR DESCRIPTION
**Pull request by nmburgan**

### CODE REVIEW

**Review by austb — APPROVED** [review]
PDB tested against clj-parent 4.9.4-SNAPSHOT using the current HEAD of its branches

**Comment by jonathannewman** [comment]
Looks good on RBAC.  Trying it on classifier now.

**Comment by donoghuc** [comment]
Looking at orchestrator now...

**Review by jonathannewman — APPROVED** [review]

**Review by donoghuc — APPROVED** [review]
Gave it a shake with orch, looks fine.

**Comment by nmburgan** [comment]
Updated to make this the 4.9.4 release

**Review by Magisus — APPROVED** [review]

**Pull request merged**
