### PR TITLE
(SERVER-2388) Update snakeyaml to latest

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Comment by Magisus** [comment]
Any adjustments need to be made in consuming projects to pick this up?

**Comment by justinstoller** [comment]
The project lists three "minor backwards-incompatible changes" https://bitbucket.org/asomov/snakeyaml/wiki/Changes though I'm unclear how and if that will affect anyone. It sounds like from the last time I brought this up that there's no one else using it: https://github.com/puppetlabs/clj-parent/pull/158  FWIW, this is a hard dependency in JRuby, newer versions require it, older versions cannot work with it.

Maybe it would be best to remove snakeyaml here and manage it individually in jruby-deps/utils then?

**Comment by Magisus** [comment]
If Jruby is the main that that tends to conflict with it, I'm kind of in favor of moving it in there, perhaps preferring jruby-utils since I know we've discussed no longer using jruby-deps at some point in the future.

**Comment by Magisus** [comment]
We're going to merge this here anyway, since the update doesn't cause problems for projects not using JRuby.

**Pull request merged**
