### PR TITLE
(PE-19944) Update clj-i18n dependency to 0.8.0

### PR DESCRIPTION
**Pull request by ajroetker**

### CODE REVIEW

**Comment by ajroetker** [comment]
Just putting this up in prep for the i18n release

**Comment by rlinehan** [comment]
@ajroetker this is ready for merge now? I'm 👍 on it.

**Comment by haus** [comment]
https://github.com/puppetlabs/clj-i18n/pull/38

**Comment by ajroetker** [comment]
@rlinehan @haus This is ready to go now!

**Pull request merged**
