### PR TITLE
(maint) Update typesafe config

### PR DESCRIPTION
**Pull request by MikaelSmith**
Upgrades to the current latest release of https://github.com/lightbend/config with an upgrade to our wrapper library. Primarily improves referencing environment variable lists.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Does 4.6.11 seem fine for this release? I'm guessing 4.6 is the line intended for PE 2019.8.

**Review by Iristyle — APPROVED** [review]

**Review by Magisus — APPROVED** [review]

**Comment by Iristyle** [comment]
Clojure project PRs:

* [ ] puppetserver - https://github.com/puppetlabs/puppetserver/pull/2481
* [ ] puppetdb
* [ ] pe-console-services
* [ ] pe-orchestration-services

**Comment by Magisus** [comment]
Don't need this update in Puppetserver (it's automated on release of this library), but we do for pe-puppet-server-extensions.

**Comment by Magisus** [comment]
Did y'all already test this in puppetserver clojure tests or should I test that out?

**Comment by MikaelSmith** [comment]
I haven't, you run those locally with the version overridden?

**Comment by Iristyle** [comment]
@Magisus I think we still have to update ruby hocon gem in puppetserver

**Comment by Magisus** [comment]
I have that in here too.

**Comment by mwaggett** [comment]
> Does 4.6.11 seem fine for this release? I'm guessing 4.6 is the line intended for PE 2019.8.

seems fine to me. fwiw, 2019.8 and main are both on the 4.6 series - we don't plan to branch unless/until we need to.

**Review by mwaggett — APPROVED** [review]

**Comment by MikaelSmith** [comment]
We should probably also get https://github.com/puppetlabs/clj-parent/pull/269 in if we're going to bump everything.

**Review by Magisus — APPROVED** [review]
This looks fine in puppetserver tests.

**Pull request merged**
