### PR TITLE
(maint) prep for 4.6.18 release

### PR DESCRIPTION
**Pull request by steveax**
Please add all notable changes to the "Unreleased" section of the CHANGELOG.

### CODE REVIEW

**Review by Magisus — APPROVED** [review]

**Review by donoghuc — APPROVED** [review]
What constitutes a `y` release for this project?

**Comment by Magisus** [comment]
It's a little hazy... Features of some of the "major" component usually. Like trapperkeeper, for example. Maybe this one too, depending on the feature and its level of impact?

**Comment by Magisus** [comment]
Though in this case, kicthensink wasn't even released as a Y, so I wouldn't do one here.

**Comment by donoghuc** [comment]
I could see it either way, it is a "bug fix" because we are using this new helper to replace a insecure dependency, but its also a feature because its a new helper.

**Comment by donoghuc** [comment]
good point

**Review by mwaggett — APPROVED** [review]

**Pull request merged**
