### PR TITLE
(ORCH-1962) Update cheshire and jackson-core versions

### PR DESCRIPTION
**Pull request by ekinanp**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Do these look like safe bumps?

**Comment by Magisus** [comment]
So I'm trying to understand our process around this project. Why does this increment the version to 1.3.4-SNAPSHOT? When I last ran the release job for this project, it stripped the `SNAPSHOT`, tagged with the resulting version, then incremented the version and added a `SNAPSHOT`. I feel like with this, we will end up skipping 1.3.3.

**Comment by ekinanp** [comment]
@Magisus That's something I'm not sure about myself too. Last time I put a PR up here, I think I bumped the version so that's why I did it again here. @MikaelSmith ?

**Comment by nicklewis** [comment]
I think we should bump the version to `1.4.0-SNAPSHOT`, which will cause the next released version to be `1.4.0`, as this is a feature bump. There's no reason to manually bump the version if we only wanted to do a z release.

**Comment by ekinanp** [comment]
@nicklewis Just bumped it.

**Comment by Magisus** [comment]
I think there is an option you can pass to the Jenkins job to do a Y release, but I haven't tried it, and of course now I can't find the job >.>

**Comment by nicklewis** [comment]
@Magisus That option actually seems to bump the Y *after* doing the release. So passing increment=minor when the version is 1.3.3-SNAPSHOT will do a 1.3.3 release and then bump to 1.4.0-SNAPSHOT. We really need to just get that fixed (it should bump to 1.4.0-SNAPSHOT and then release) so we never have to manually touch a version number again...

**Comment by Magisus** [comment]
Ahhh okay yeah that description is really misleading then. It seemed really cool, it'd be nice to fix that.

**Comment by MikaelSmith** [comment]
If we're preparing for the release, also add a CHANGELOG entry?

**Comment by ekinanp** [comment]
@MikaelSmith Done

**Pull request merged**
