### PR TITLE
(SERVER-2205) Upgrade ssl-utils to 1.0.0

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Comment by Magisus** [comment]
Are you going to do the release prep in a separate PR?

**Comment by justinstoller** [comment]
I was putting up everything I had in progress in individual PRs so I could dig deeper into the issues I was seeing locally, not knowing what was actually going to land or where.

With the clojurescript PR closed, and a work around found for pulling in clj-parent 2.0.0, I can put the release notes in here.

**Comment by Magisus** [comment]
You mentioned that other people might need the same workaround. Is there a way we could communicate that? I realize it affects the version before this PR, so not here, but in general?

**Comment by justinstoller** [comment]
I thought about sending something out to dev, though I'd like to come back to SERVER-2216 in a minute or have someone else try to repro before sending something out.

**Pull request merged**
