### PR TITLE
(maint) Prepare 4.0.0 release

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Comment by justinstoller** [comment]
Putting this here while I run some tests locally

**Comment by Magisus** [comment]
The notes look good, let me know when the testing is done.

**Comment by justinstoller** [comment]
Puppet Server tests pass with this, lets do it!

**Comment by Magisus** [comment]
Did you have to do namespace changes or does it just work?

**Comment by justinstoller** [comment]
No I just had to change the artifact group ids, no code changes.

**Pull request merged**
