### PR TITLE
(PE-26658) Update version of bc fips

### PR DESCRIPTION
**Pull request by robdaemon**
release new clj-parent with updated bc fips jars

### CODE REVIEW

**Comment by robdaemon** [comment]
I'm assuming I'm doing this right for this repo? This will get us a release build. and next I'll open a PR that bumps to to the next snapshot version?

**Comment by MikaelSmith** [comment]
I'm not sure this is how releases are done. We generally have release automation that will remove -SNAPSHOT, tag the release, then bump to a new snapshot.

**Comment by MikaelSmith** [comment]
https://cinext-jenkinsmaster-enterprise-prod-1.delivery.puppetlabs.net/view/clojure-libraries/view/all/job/enterprise_clj-parent_release-clj_master/ if you're on our VPN.

**Comment by MikaelSmith** [comment]
The commit title doesn't seem consistent with what this PR's doing.

https://github.com/puppetlabs/clj-parent#releases still seems correct. If this is a Z-release, no need for a pull request to do the release.

**Comment by steveax** [comment]
Yep, use the Jenkins job ^^.

**Comment by robdaemon** [comment]
okiedokie, thank you!

**Pull request closed without merging**
