### PR TITLE
(maint) Bump clj-shell-utils

### PR DESCRIPTION
**Pull request by tvpartytonight**

### CODE REVIEW

**Comment by Magisus** [comment]
Looks like there was maybe no content in the diff between 1.0.0 and 1.0.2? What happened there? And if that's true, do we need this now, or can we wait till there are actual changes and then go to 1.0.3?

**Comment by tvpartytonight** [comment]
I built 1.0.0 locally, but with java11; that's the only difference between these versions. I should add the release note though!

**Comment by Magisus** [comment]
Yes please :) That was going to be my next comment if it turned out this was necessary. Thanks.

**Comment by Magisus** [comment]
Can you also update the changelog in this project?

**Pull request merged**
