### PR TITLE
(maint) Add PR template to remind people to update the changelog

### PR DESCRIPTION
**Pull request by mwaggett**

### CODE REVIEW

**Comment by Magisus** [comment]
While using an "unreleased" section does communicate the actual state better, I feel like someone is definitely going to tag this with that still in there (having forgotten to update it to the proper version). Are we okay with that?

(side note, updating "unreleased" to "tag version" would be a good place for automation)

**Comment by mwaggett** [comment]
The way we've done it on RE is that we keep the "Unreleased" section there always but when we're doing a release, we just add the tag version above all the unreleased changes (so it looks like it does now). I don't know what the process for releasing this looks like, so not sure how likely it is that we'll forget.

**Comment by Magisus** [comment]
Ah makes sense about keeping that section around always.

The process here is to run a one-step [Jenkins job](https://cinext-jenkinsmaster-enterprise-prod-1.delivery.puppetlabs.net/view/clojure-libraries/view/all/job/enterprise_clj-parent_release-clj_master/), that will automatically tag based on the current SNAPSHOT version, push to clojars, and update to the next SNAPSHOT version.

This is usually done by someone who has merged a change they want to use immediately, after the 30-second test pipeline finishes (this repo has no tests at pesent). I mostly worry because generally, the process is pretty mindless right now (hence why sometimes the changelog doesn't get updated).

That being said, I'm fine adding this step to the process. It forces the person who wants to release to be a little more cognizant of checking that the changelog is updated and that they are releasing the version they want (e.g. Y vs. Z).

**Comment by branan** [comment]
Does this repo even need a changelog? It's released pretty frequently, and by its nature all changes are the same thing (dependency bumps). This makes a `git log` even more straightforward than on most repos.

I often question the value of changelogs when git history is available, but it seems even less useful here

**Comment by branan** [comment]
I also agree that PR templates become noise - I'm sure I wouldn't notice if the one for cjc changed, since I'm used to skipping over it by now.

**Comment by robdaemon** [comment]
I agree with branan here, I'm one of the guilty ones who forgets to update this changelog unless reminded. The changelog entries don't have the level of detail the git log does. I'm just used to viewing a git log.

**Comment by jonathannewman** [comment]
I disagree that it isn't useful.  I find the changelog much easier to parse and understand at a glance from the github UI than working through git logs in the UI.  We could certainly advocate for more information in the changelog, and honestly, I find a lot of the git commit messages lacking.

**Comment by mwaggett** [comment]
imo, commit messages should have **more** detail than a changelog - changelogs are for users of the library, commit messages are for developers (loosely).
I do kind of agree that the changelog doesn't seem especially useful, but then we would need to be better about writing detailed (but concise) commit messages.

**Comment by Magisus** [comment]
I agree with Jonathan that the changelog is easier to read, and usually use it first when trying to figure out what all has happened recently in this lib. Most of the time I don't need more detail than what updated and the primary reason for the update. But if we wanted to do away with it, I'd get used to reading the log 🤷‍♀

**Comment by mwaggett** [comment]
so it sounds like our options are:
1. eliminate the changelog entirely, in favor of detailed, but concise commit messages
2. add this template in the hopes that it will remind folks to update the changelog when they open a PR (knowing that we may accidentally leave changes in the 'Unreleased' section when we ship)
3. leave things as they are (knowing that we often forget to add changes to the changelog, so it may be out-of-date and need ad-hoc updates at any time)

Thoughts?

**Comment by jonathannewman** [comment]
Either #2 or #3 in your list @mwaggett  work for me.

**Comment by robdaemon** [comment]
I'm in favor of the first option. PuppetDB and the PuppetDB extensions don't use a changelog. We rely on the git commit messages.

I find when I look at changelogs of other libraries / products, the partial sentence blurb is never enough to give me context on the change. It would have to be linked to a larger ticket / bug report / change for me to understand. In this case, that just leads me back to the git log every time.

**Comment by steveax** [comment]
I don't have strong feelings about it, but I'd go with removing. An unreliable changelog doesn't seem too valuable to me.

**Comment by mwaggett** [comment]
okay, since there are folks that use the changelog, I think we should go with #2 (i.e. merge this PR) for now and we can revisit option #1 down the line if we continue to find ourselves with an out-of-date changelog. Does that seem reasonable?

**Comment by mwaggett** [comment]
retargeted at 1.7.x

**Pull request merged**
