### PR TITLE
(maint) Update clj-yaml to a maintained version

### PR DESCRIPTION
**Pull request by haus**
circleci/clj-yaml is a maintained version of the original clj-yaml
project that was last updated in 2012. This commit updates the
dependency to circleci's fork.

### CODE REVIEW

**Comment by camlow325** [comment]
@haus Are there any compatibility issues that you'd expect on bringing this in?  I'm open to doing it.  Just curious if there was something specific you were hoping to get with this other than just moving us up to using a supported version.

**Comment by haus** [comment]
@camlow325 i opened this because code-manager uses a more recent version of clj-yaml and i wanted to use clj-parent there to resolve the version (https://github.com/puppetlabs/code-manager/blob/glisan/project.clj#L34).

I'll look through the changes since 0.4.0 to make sure there haven't been any api breaks. If this gets merged, projects consuming clj-yaml will need to update their project.clj to move the artifact name, but any requires and fn calls should not need changing.

**Comment by haus** [comment]
Looking at the changes, the most prominent of them were using `ordered-map` and `ordered-set` instead of the clojure defaults (https://github.com/lancepantz/clj-yaml/commit/b90fdbaca84f0b38b90b1f19762b62d80a98f495) and changing a keyword arg from `:keywordize` to `:keywords` (https://github.com/lancepantz/clj-yaml/commit/aee5f4ddc12a5e13f85e48667a08040946e91bf1).

**Comment by camlow325** [comment]
Maybe it doesn't matter too much, but I'm not sure how active the circleci fork is either since it hasn't had any commits to its master branch in over a year.  Still updated 3 years more recently than the original project, though.

I did some spot checking of different repos with this and didn't see any obvious issues either.  I ran all of the unit tests for trapperkeeper and puppetserver with `circleci/clj-yaml` version 0.5.5 and didn't see any failures.

@haus Think it's worth having anyone else review this before I push the button?

**Comment by haus** [comment]
@camlow325 :man_shrugging: :woman_shrugging: I think it's probably fine to just merge

**Pull request merged**
