### PR TITLE
(maint) update ring dependencies to latest

### PR DESCRIPTION
**Pull request by steveax**
- ring/ring-servlet "1.8.2"
- ring/ring-core "1.8.2"
- ring/ring-codec "1.1.2"
- ring/ring-json "0.5.0"
- ring-basic-authentication "1.1.0"
- ring/ring-mock "0.4.0"
- ring/ring-defaults "0.3.2"

Please add all notable changes to the "Unreleased" section of the CHANGELOG.

### CODE REVIEW

**Comment by steveax** [comment]
I ran the tests with this on tk-j9-webserver and orchestrator.

**Review by justinstoller — APPROVED** [review]
pe-puppet-server-extensions#main passed with this

**Review by donoghuc — APPROVED** [review]

**Comment by MikaelSmith** [comment]
This could use a section in CHANGELOG, but can handle that when preparing the release.

**Comment by Iristyle** [comment]
As a follow-up, this caused some issues in how errors propagate in `puppetserver` itself - https://github.com/puppetlabs/puppetserver/pull/2481#issuecomment-764851704

@Magisus is working on a PR there

**Pull request merged**
