### PR TITLE
(SERVER-3219) Update JRuby via jruby-utils

### PR DESCRIPTION
**Pull request by justinstoller**
Please add all notable changes to the "Unreleased" section of the CHANGELOG.

### CODE REVIEW

**Comment by steveax** [comment]
Is 3219 the right ticket number?

**Comment by jonathannewman** [comment]
@justinstoller can you rebase?

**Comment by justinstoller** [comment]
Oh, sorry, Steve didn't see that comment. It's not a great ticket, it addresses the issue I saw in https://tickets.puppetlabs.com/browse/SERVER-3219?focusedCommentId=874462&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-874462 . I'm fine saying that warrants its own ticket and number if you think that's best.

**Comment by steveax** [comment]
@justinstoller, no need for another ticket.

**Comment by jonathannewman** [comment]
@justinstoller  now that things have settled, does this still make sense to land?

**Comment by justinstoller** [comment]
Ish. We need to upgrade JRuby, though now this should be superseded by our work for 9.3.9 (assuming that's going to happen before the next FOSS release).

**Comment by jonathannewman** [comment]
Closing in favor of https://github.com/puppetlabs/clj-parent/pull/370

**Pull request closed without merging**
